### ISSUE TITLE
numba 0.54 constraints break anaconda 2021.11

### ISSUE THREAD

**Issue by bombaci-vsc** [AnacondaRecipes/repodata-hotfixes#172]
The new numba constraints introduced in #170 seem to have broken the ability to install anaconda=2021.11.

```
$ conda create -n myenv anaconda=2021.11
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - anaconda=2021.11 -> libgcc-ng==9.3.0=h5101ec6_17 -> __glibc[version='>=2.17']

Your installed version is: 2.35
```
While the error message is cryptic it appears to be happening because Anaconda 2021.11 apparently shipped with incompatible versions of numpy and numba, which #170 now makes impossible to install:

```
$ conda search --info anaconda=2021.11=py39_0|grep 'numpy \|numba '
  - numba 0.54.1 py39h51133e4_0
  - numpy 1.20.3 py39hf144106_0
```

Is the ability to install old versions of Anaconda something users should expect to be possible?

**Comment by bombaci-vsc** [comment]
@cbouss Thank you for addressing the problem so quickly.  The fix in #173 looks like it should resolve the problem.  Is there an ETA or any way to predict when the change will propagate into the main linux-64 channel https://repo.anaconda.com/pkgs/main/linux-64/ ?

Are we at the mercy of waiting for the next time a package gets added to the channel?  or is there a way to trigger a re-indexing and/or re-hotfixing?

**Comment by cbouss** [comment]
Hi @bombaci-vsc, thank you for your patience.
We had to wait for a maintenance task to complete before re-indexing but the issue should now be solved.

**Comment by bombaci-vsc** [comment]
I see the change is now live.  Thank you again for the quick turnaround.
