### ISSUE TITLE
anaconda 5.3 is not installable

### ISSUE THREAD

**Issue by nehaljwani** [AnacondaRecipes/repodata-hotfixes#26]
```
numpy=1.15.1=py37h1d66e8a_0 (in installer) (depends)              -> numpy-base 1.15.1 py37h81de0dd_0 (TS: 2018-08-27 17:10:45 UTC)
numpy=1.15.1=py37h3b04361_0 (not in installer) (depends)          -> numpy-base 1.15.1 py37h81de0dd_0 (TS: 2018-08-27 17:11:26 UTC)
numpy-base=1.15.1=py37h81de0dd_0 (in installer) (run constraints) -> numpy 1.15.1 py37h3b04361_0 (not in installer)

numpy 1.15.1 py27h1d66e8a_0 (in installer) (depends)              -> numpy-base 1.15.1 py27h81de0dd_0 (TS: 2018-08-27 22:06:22 UTC)
numpy 1.15.1 py27h3b04361_0 (not in installer) (depends)          -> numpy-base 1.15.1 py27h81de0dd_0 (TS: 2018-08-27 17:11:13 UTC)
numpy-base=1.15.1=py27h81de0dd_0 (in installer) (run constraints) -> numpy 1.15.1 py27h3b04361_0 (not in installer)

numpy 1.15.1 py36h1d66e8a_0 (in installer) (depends)              -> numpy-base 1.15.1 py36h81de0dd_0 (TS: 2018-08-27 21:58:49 UTC)
numpy 1.15.1 py36h3b04361_0 (not in installer) (depends)          -> numpy-base 1.15.1 py36h81de0dd_0 (TS: 2018-08-27 17:11:21 UTC)
numpy-base=1.15.1=py36h81de0dd_0 (in installer) (run constraints) -> numpy 1.15.1 py36h3b04361_0 (not in installer)
```

I say we revoke `numpy=1.15.1=py*h3b04361_0`. The ones which actually went into the installer were built later that same day.

**Comment by mcg1969** [comment]
Priority needs to be given to making the metapackage correct IMO.

**Comment by msarahan** [comment]
I think we need to hotfix what we have to make it consistent, rather than revoking anything. I think that means fixing the run_constrains. 

Is that what you're saying, @mcg1969 or are you just saying you want a fix ASAP?

**Comment by mcg1969** [comment]
I agree with you, Michael. I'm not sure revoking is the right path forward, because creating inconsistent environments for people is itself a problem.

**Comment by nehaljwani** [comment]
If we fix the `run_constrains` of the numpy-base package and point it to the one in the installer, then the other numpy (which I am asking to revoke) will become uninstallable.

**Comment by mcg1969** [comment]
I might be missing something, but `conda install anaconda=5.3` is uninstallable _now_. I _think_ it is important to make that metapackage installable again, without changing its contents, because (for instance) AE5.3 has it installed. So what happens is that simple `conda` commands end up scheduling significant environment modifications to fix the inconsistency, and that is a particularly harsh medicine.

**Comment by nehaljwani** [comment]
Alright, 0 hot-fixing. I just uploaded a newer build of the metapackage.

@mcg1969 Does: `conda install nwani::anaconda=5.3` work for you?

**Comment by mcg1969** [comment]
checking now

**Comment by mcg1969** [comment]
@nehaljwani no conflicts reported. thanks!

**Comment by nehaljwani** [comment]
The new metapackages for py27 and py37 are available now.

**Comment by nehaljwani** [comment]
A new metapackage for py36 has also been made available now.
